### ISSUE TITLE
true, false, null inputs remain as strings instead of being converted to pythonic types

### ISSUE THREAD

**Issue by ariannedee** [ivelum/graphql-py#10]
When parsing a GraphQL document, special inputs (`true`, `false`, `null`) should be parsed differently from `"true"`, `"false"`, and `"null"` and should instead be returned as `True`, `False`, `None` instead of strings.

e.g.
```
{
  field (name: null) {
    field2
  }
}
```

should return an argument of None 
```
{
  field (name: "null") {
    field2
  }
}
```

should return an argument of "null"

**Comment by stebunovd** [comment]
Thank you for the contribution!

**Comment by stebunovd** [comment]
version 0.7.0 is on PyPI

**Comment by ariannedee** [comment]
Thank you!
