### ISSUE TITLE
Rendering AST to GraphQL String?

### ISSUE THREAD

**Issue by mhoffman** [ivelum/graphql-py#11]
Is there a simple method to convert a parser AST object back into its corresponding GraphQL string?  Possibly after some manipulation of the AST.  Example:

    >>> parser = graphql.parser.GraphQLParser()
    >>> s = parser.parse("""{systems(first: 10) {
    ...   edges {
    ...     node {
    ...       id
    ...     }
    ...   }
    ... }}""")
    >>> s
    <Document: definitions=[<Query: selections=[<Field: name=systems, arguments=[<Argument: 
    name=first, value=10>], selections=[<Field: name=edges, selections=[<Field: name=node, selections= 
    [<Field: name=id>]>]>]>]>]>
    >>> graphql.render(s)
    {systems(first: 10) {
      edges {
        node {
          id
        }
      }
    }}

I guess I could tweak all the `__repr___` methods in such a way, but it seems that I am missing something?

**Comment by stebunovd** [comment]
Could you please tell more about the use case? Is this just for better aesthetics for Document representation, or do you have a case in your app when you construct AST dynamically (and not from source), or..?

**Comment by mhoffman** [comment]
I have the following scenario: I want to accept any GraphQL query from client but I want to add a filter on the fly on the backend. (e.g. username in a multi-tenant setup). So my plan was to (1) take the incoming query, (2) parse query with graphql-py, (3) amend resulting AST, (4) render new graphql query, (5) run against db. Does that make sense?

**Comment by stebunovd** [comment]
why not just apply the filter on SQL/ORM level when you are ready to run the query against the DB? Sounds much simpler for me. Also, it should have better performance, due to avoiding duplicated GraphQL parsing

**Comment by mhoffman** [comment]
Agreed. In my case performance is not critical but I found a workaround. Thanks.
