### ISSUE TITLE
Variable parsing

### ISSUE THREAD

**Issue by millerjs** [ivelum/graphql-py#4]
Example query using variables fails parsing
```
query getZuckProfile($devicePicSize: Int) {
  user(id: 4) {
    id
    name
    profilePic(size: $devicePicSize)
  }
}
```
with `Invalid query: Line 1, col 36: Syntax error at u':'`

**Comment by stebunovd** [comment]
Thank you for bug report and pull request. Merged and released version 0.6.0 with this fix.
